--- #YAML:1.0
name:               Net-SMS-Cellsynt
version:            0.2
abstract:           Send SMS through Cellsynt SMS gateway
author:
    - Olof Johansson <zibri@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    URI::Escape:      0
    WWW::Curl::Easy:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
